### ISSUE TITLE
Inconsistant link detection

### ISSUE THREAD

**Issue by Warths** [MyTheValentinus/twitch-bot#6]
The bot link detection logic pretty much look like this : 
If there's any character, then a ".", then any character, this is considered to be a link.

That's not an issue as long as people know how to write, or if it's not a programing show.

the link detection should detect a link as long as it has a domain extention that is part of the International Domain Extension list : 
**https://iwantmyname.com/domains/domain-name-registration-list-of-extensions**
and should be able to detect, at least, raw ipv4 aswell. (exemple : 192.168.1.1)

A cool improvement could be to make it impossible to passthrougth via the most common method, putting space next to dots like so :

 www . twitch . tv

**Comment by vdeville** [comment]
Hello @Warths and thanks for your request.
I already work on link detection improvement and propose new regex option to Antispam module for choose regex to use.

**Comment by vdeville** [comment]
Done in dev branche. Release in next release
