### ISSUE TITLE
Subhype Month Calculation Issue

### ISSUE THREAD

**Issue by mahony0** [MyTheValentinus/twitch-bot#8]
Hi,

There's an issue with string replacing on SubHype module.

https://github.com/MyTheValentinus/twitch-bot/blob/c986d96e620f9234b40e3f09f66b38ff8924c177/modules/subhype/Subhype.php#L50 

It should be:
```php
$months = str_replace('msg-param-cumulative-months=', '', $months);
```

I can send PR if you approve this is an issue.

Thanks for your efforts.

**Comment by vdeville** [comment]
Hello,

Thanks you for your report !
Yeah with pleasure, send a PR i will approve it now !

Thanks !
